{
 "title": "Rover Dashboard",
 "tags": [
  "SolarThing",
  "Rover"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data Source",
    "query": "retrodaredevil-wildgraphql-datasource"
   },
   { "name": "fragmentId", "label": "Fragment ID", "query": "2" },
   { "name": "identifier", "label": "Identifier", "query": "RoverIdentifier()" }
  ]
 },
 "panels": [
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        batteryVoltage\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Charging Wattage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        chargingPower\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Daily kWh",
   "type": "stat",
   "description": "The amount of energy put into the batteries from the solar panels today. This value is reset when the Rover starts charging in the morning.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        dailyKWH\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        batteryTemperatureFahrenheit\n        controllerTemperatureFahrenheit\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Device Info",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        productSerialNumber\n        ratedChargingCurrent\n        ratedDischargingCurrent\n        softwareVersion {\n          representation\n        }\n        hardwareVersion {\n          representation\n        }\n        productModelString\n        controllerDeviceAddress\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Operating Days Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        operatingDaysCount\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Load Wattage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        loadPower\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Daily kWh Consumption",
   "type": "stat",
   "description": "The amount of energy supplied by the Rover's load terminals today. This resets in the morning.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        dailyKWHConsumption\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Charge Controller State",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId,\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        solarModeTypeDisplayName\n        loadWorkingMode\n        dailyMaxChargingPower\n        dailyMaxDischargingPower\n        dailyMaxBatteryVoltage\n        dailyMinBatteryVoltage\n        dailyAH\n        dailyAHDischarging\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        batteryVoltage\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Charging Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        chargingPower\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        batteryTemperatureFahrenheit\n        controllerTemperatureFahrenheit\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Discharging Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        loadPower\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "Daily Generation and Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        dailyKWH\n        dailyKWHConsumption\n        dailyAH\n        dailyAHDischarging\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  },
  {
   "title": "PV Current and PV Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "data.roverStatus",
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "displayName",
         "type": "field",
         "value": "packet.identityInfo.displayName"
        }
       ],
       "timeFields": [
        { "timePath": "dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!, $fragmentId: Int!, $identifier: String!) {\n  data: queryStatusIdentifier(\n    from: $from\n    to: $to\n    fragmentId: $fragmentId\n    identifier: $identifier\n  ) {\n    roverStatus {\n      dateMillis\n      packet {\n        pvCurrent\n        pvVoltage\n        identityInfo {\n          displayName\n        }\n      }\n    }\n  }\n}",
     "variables": "{\n  \"identifier\": \"$identifier\"\n}",
     "variablesWithFullInterpolation": "{\n  \"fragmentId\": $fragmentId\n}"
    }
   ]
  }
 ]
}